### ISSUE TITLE
Project description is needed

### ISSUE THREAD

**Issue by AlexDaniel** [FCO/6pm#10]
I looked at the readme on https://github.com/FCO/6pm and in the first minute couldn't figure out what's the goal of the project.

I think a sentence or two describing the goals of the project can make things easier for contributors/users.

Also, the description on github needs to be set also:
![image](https://user-images.githubusercontent.com/5507503/46574500-ffebc700-c9ac-11e8-9ee3-49933d0be7fd.png)

**Comment by FCO** [comment]
Thanks! That a good idea! I’ll do that!
